SELECT t2.JOB_TITLE AS Cargo,
ROUND(AVG(SALARY), 2) AS `Média salarial`,
CASE
WHEN ROUND(AVG(SALARY)) BETWEEN 2000 AND 5800 THEN 'Júnior'
WHEN ROUND(AVG(SALARY)) BETWEEN 5801 AND 7500 THEN 'Pleno'
WHEN ROUND(AVG(SALARY)) BETWEEN 7501 AND 10500 THEN 'Sênior'
WHEN ROUND(AVG(SALARY)) > 10500 THEN 'CEO'
ELSE ''
END AS Senioridade
FROM employees AS t1
INNER JOIN jobs AS t2
ON t1.JOB_ID = t2.JOB_ID
GROUP BY Cargo
ORDER BY `Média salarial` ASC, Cargo;
